---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Prefix:
    Type: String
Resources:
  CfnRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${Prefix}-cfn-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Sub "arn:aws:iam::${AWS::AccountId}:role/AccountAdministrator"
            Action:
              - "sts:AssumeRole"   
          - Effect: Allow
            Principal:
              Service:
                - "cloudformation.amazonaws.com"
            Action:
              - "sts:AssumeRole"   
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess"
        - "arn:aws:iam::aws:policy/AWSLambdaReadOnlyAccess"
      Policies:
        - PolicyName: AllowLambdaManipulation
          PolicyDocument:
            Version: 2012-10-17
            Statement:
            - Effect: Allow
              Action:
                - 'lambda:TagResource'
                - 'lambda:UntagResource*'
                - 'lambda:ListTags'
              Resource:
                - '*'
            - Effect: Allow
              Action:
                - 'lambda:*'
              Resource:
                - !Sub "arn:aws:lambda:us-west-2:${AWS::AccountId}:function:${Prefix}-*"
            - Effect: Allow
              Action:
                - 'iam:GetRole'
                - 'iam:PassRole'
              Resource:
                - !GetAtt LambdaRole.Arn

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${Prefix}-lambda-role"
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"

Outputs:
  CfnRoleArn:
    Value: !GetAtt CfnRole.Arn

